apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  namespace: gerald-env
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice-product
  template:
    metadata:
      labels:
        app: microservice-product
    spec:
      containers:
      - name: product
        image: microservice-product
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5004