apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: gerald-env
spec:
  selector:
    app: microservice-frontend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 32310
  type: NodePort