apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: gerald-env
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice-backend
  template:
    metadata:
      labels:
        app: microservice-backend
    spec:
      containers:
      - name: backend
        image: microservice-backend
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5003