apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: gerald-env
spec:
  selector:
    app: microservice-backend
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
    #  nodePort: 30011
#  type: NodePort
